### ISSUE TITLE
Support for darwin_arm64 (M1)

### ISSUE THREAD

**Issue by ZdenT** [Kaginari/terraform-provider-mongodb#21]
It would be nice to create also build for darwin_arm64 platform.

**Comment by ITMonta** [comment]
@ZdenT   thanks to @sollie  you have an available  darwin_arm64 for Version 1.4.0 (published)
https://registry.terraform.io/providers/Kaginari/mongodb/0.1.4

**Comment by ZdenT** [comment]
Thank you guys! Good work.
