### ISSUE TITLE
Not updating/deleting users correctly

### ISSUE THREAD

**Issue by andiempett** [Kaginari/terraform-provider-mongodb#3]
The provider cannot update a users role and results in an error. Also on destroy the user isn't destroyed.

in the `resourceDatabaseUserUpdate` function there is this:
```
adminDB := client.Database("admin")
Users := adminDB.Collection("system.users")
```

these are hardcoded and may not apply to all mongodbs. this results in an error where the user isnt deleted and the new create user cant fire as the user already exists

**Comment by ITMonta** [comment]
Thank you for your feedback, i will look into the destroy function. any use case or specific mongodb version  that can help study the behaviour ?

**Comment by ITMonta** [comment]
Thank you for the contribution  @androidwiltron   version 0.0.5 is available :+1: 
https://registry.terraform.io/providers/Kaginari/mongodb/latest/docs?pollNotifications=true
