### ISSUE TITLE
Connect to a documentDB database

### ISSUE THREAD

**Issue by viyullas** [Kaginari/terraform-provider-mongodb#5]
This is more a question than an issue.

If I configure the provider to connect to an AWS documentDB database it fails. I think it is due to the ssl certificate I have to provide to be able to identify the server. 

Is there any way I can pass this certificate to the provider? Because just enabling ssl don't resolve the problem.

**Comment by andiempett** [comment]
Hi @viyullas you'll need two things here.
1. as you said, you will need the documentDB RDS CA certificate. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html. you will need to come up with a way of bundling this into the CA certs of the operating system you are executing the terraform from. MacOS: these can be added (and trusted) in the keychain. for linux: you can do something like this: 
```
wget https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem -O /usr/local/share/ca-certificates/rds-ca-2019-root.crt
wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem -O /usr/local/share/ca-certificates/rds-combined-ca-bundle.crt
wget https://s3.amazonaws.com/rds-downloads/rds-ca-2019-eu-west-1.pem -O /usr/local/share/ca-certificates/rds-ca-2019-eu-west-1.crt
chmod 644 -R /usr/local/share/ca-certificates/rds*
update-ca-certificates
```

2. you also need to use the very latest version of this provider which has fixes in to allow it work work with DocumentDB. there is no release yet so you would need to compile from source look at the [make file](https://github.com/Kaginari/terraform-provider-mongodb/blob/f8ac1018082442deb99bb6ac243061edcfa655aa/Makefile#L20)

**Comment by viyullas** [comment]
Thanks for the info. I will try to meke it work locally with the compiled version, but to integrate it in the CI pipeline I would prefer to wait for the realsed version. Do you have an estimated time for it?

**Comment by andiempett** [comment]
> Thanks for the info. I will try to meke it work locally with the compiled version, but to integrate it in the CI pipeline I would prefer to wait for the realsed version. Do you have an estimated time for it?

@ITMonta may be able to answer that one. there is a github workflow for releases but it doesn't seem to be responsible for the latest releases - must be a manual process

**Comment by viyullas** [comment]
The I hope @ITMonta give us some good news soon....

**Comment by ITMonta** [comment]
@viyullas , thank you for the interest , I am working on the next release version to support CA certs in the provider configuration.
this should solve your problem :) 
Thanks to the fix proposed by @androidwiltron  the next release will allow also  working  with DocumentDB.
the next version will be available soon , big thanks for your support and contribution 👍

**Comment by viyullas** [comment]
Great! Waiting for it!

**Comment by ITMonta** [comment]
Version 0.0.5  is ready should include tls support and the proposed fix by @androidwiltron  
Thank you for your support :) 

https://registry.terraform.io/providers/Kaginari/mongodb/latest/docs?pollNotifications=true#certificate-information-

**Comment by viyullas** [comment]
I am sorry, but I cannot figure out how to connect to a documentDB database with the provider.
I am provided with a certificate chain form aws (https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem)
And thas the only thing I have. So, how I am supposed to use it to connect with tls support using your provider?

This is my first approach to mongoDB databases so I am probably missing something...

as this is issue closed i will open a new one.

**Comment by andiempett** [comment]
Ok so looking into this a little bit. i see the options added in https://registry.terraform.io/providers/Kaginari/mongodb/latest/docs?pollNotifications=true#certificate-information-

i ttthink there is an assumption here that your CA file is encrypted and must need a key and cert to use it. see how this works from the mongodb cli docs https://docs.mongodb.com/manual/reference/program/mongo/#cmdoption-mongo-tlscertificatekeyfilepassword (sorry i cant find the golang equivalent but it explains it i think)

```
Use the --tlsCertificateKeyFilePassword option only if the certificate-key file is encrypted. In all cases, the mongo will redact the password from all logging and reporting output.
```

the docdb CA cert is not encrypted right so you dont need that functionallity but it think that is assumed with the feature added.

did you try adding the certs to you OS ca-certs/keychain as i mentioned  above @viyullas because that works 100% (at least with the last version of the provider)

**Comment by viyullas** [comment]
> did you try adding the certs to you OS ca-certs/keychain as i mentioned above @viyullas because that works 100% (at least with the last version of the provider)

Yes, it works on my ubuntu, I am waiting for a chance to try on the deploy pipeline that runs on an alpine, but I don't expect any surprise there... 
Just wanted to understand if I was doing something wrong, but reading your explanation I assume I am not and it is just lacking this use case.

**Comment by ITMonta** [comment]
@androidwiltron  thank you for the explanation , I assumed the certificate would be encrypted. 
Thank you for the documentation [docs](https://docs.mongodb.com/manual/reference/program/mongo/#cmdoption-mongo-tlscertificatekeyfilepassword ) 
@viyullas  Can you provide me a use case ? 
Thank you @androidwiltron  and @viyullas   again for the feedback.

**Comment by viyullas** [comment]
> @viyullas Can you provide me a use case ?

When I create a documentDB cluster on AWS what I get is a link to download the ca certificate bundle, and a connection string:

```
wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
mongo --ssl --host <server name>:27017 --sslCAFile rds-combined-ca-bundle.pem --username <username> --password <insertYourPassword>

```
So with this data I can not use the provider. I have tried to use cert_path pointing to a directory where i left the downloaded pem, but I just get an error stating the tls connection cannot be stablished.

**Comment by sohel2020** [comment]
@ITMonta  
Please also allow `--tlsAllowInvalidCertificates`  flag because if it try to connect with ssh tunnel (localhost) then it returns
```connection attempt failed: SSLHandshakeFailed: SSL peer certificate validation failed: Certificate trust failure: Host name mismatch; connection rejected```

**Comment by sohel2020** [comment]
@ITMonta 

I have tried with `--sslAllowInvalidHostnames`  flag but it didn't work.  only `--tlsAllowInvalidCertificates` works.

**Ref:** https://docs.aws.amazon.com/documentdb/latest/developerguide/connect-from-outside-a-vpc.html.

this is badly needed if I want to run terrafrom from my local machine for private subnet aws documentdb.

**Comment by ITMonta** [comment]
@sohel2020  i noted your issue , 
Thank you  for your feedback

**Comment by ITMonta** [comment]
Version v0.0.6  released 

@viyullas  Problem resolved you should be able to test  (specify you cert_path and your .pem file should be named ca.pem under the cert path )

@sohel2020   added insecure_skip_verify param in config to ignore hostname verification

thank you all for your feedback  , excuse me for the late :)
